{
  "elements": {
    "alkali_metals": [
    {
      "name": "Hydrogen",
      "symbol": "H",
      "atomic_number": 1,
      "atomic_mass": 1.008,
      "summary": "Hydrogen is the lightest and most abundant element in the universe. It is a colorless, odorless, and highly flammable gas.",
      "founded_by": "Henry Cavendish",
      "state_of_matter": "Gas",
      "melting_point": -259.16,
      "group": 1,
      "period": 1,
      "density": 0.08988,
      "ionization_energy": 1312,
      "electron_configuration": "1s1",
      "uses": "Used in the production of ammonia, hydrogen peroxide, and as rocket fuel.",
      "picture": "hydrogen.jpg"
    },
    {
      "name": "Lithium",
      "symbol": "Li",
      "atomic_number": 3,
      "atomic_mass": 6.94,
      "summary": "Lithium is a soft, silvery-white alkali metal. It is highly reactive and can ignite spontaneously in air.",
      "founded_by": "Johan August Arfwedson",
      "state_of_matter": "Solid",
      "melting_point": 180.54,
      "group": 1,
      "period": 2,
      "density": 0.534,
      "ionization_energy": 520.2,
      "electron_configuration": "[He] 2s1",
      "uses": "Used in batteries, as a mood stabilizer in medicine, and for nuclear fusion reactions.",
      "picture": "lithium.jpg"
    },
    {
      "name": "Sodium",
      "symbol": "Na",
      "atomic_number": 11,
      "atomic_mass": 22.99,
      "summary": "Sodium is a highly reactive, soft metal that tarnishes quickly in air. It is an essential element for life.",
      "founded_by": "Humphry Davy",
      "state_of_matter": "Solid",
      "melting_point": 370.87,
      "group": 1,
      "period": 3,
      "density": 0.968,
      "ionization_energy": 495.8,
      "electron_configuration": "[Ne] 3s1",
      "uses": "Used in various chemical processes, in table salt (sodium chloride), and in the production of soap.",
      "picture": "sodium.jpg"
    },
    {
      "name": "Potassium",
      "symbol": "K",
      "atomic_number": 19,
      "atomic_mass": 39.1,
      "summary": "Potassium is a soft, silvery-white metal that is highly reactive with water. It plays a crucial role in biological processes.",
      "founded_by": "Humphry Davy",
      "state_of_matter": "Solid",
      "melting_point": 336.53,
      "group": 1,
      "period": 4,
      "density": 0.862,
      "ionization_energy": 418.8,
      "electron_configuration": "[Ar] 4s1",
      "uses": "Used in fertilizers, as a nutrient in plant and animal nutrition, and in some medicines.",
      "picture": "potassium.jpg"
    },
    {
      "name": "Rubidium",
      "symbol": "Rb",
      "atomic_number": 37,
      "atomic_mass": 85.47,
      "summary": "Rubidium is a soft, silvery-white alkali metal. It is highly reactive and can ignite spontaneously in air.",
      "founded_by": "Robert Bunsen and Gustav Kirchhoff",
      "state_of_matter": "Solid",
      "melting_point": 312.46,
      "group": 1,
      "period": 5,
      "density": 1.532,
      "ionization_energy": 403.0,
      "electron_configuration": "[Kr] 5s1",
      "uses": "Used in some atomic clocks and in research applications.",
      "picture": "rubidium.jpg"
    },
    {
      "name": "Cesium",
      "symbol": "Cs",
      "atomic_number": 55,
      "atomic_mass": 132.91,
      "summary": "Cesium is a soft, silvery-white alkali metal. It is highly reactive and can ignite spontaneously in air.",
      "founded_by": "Robert Bunsen and Gustav Kirchhoff",
      "state_of_matter": "Solid",
      "melting_point": 301.59,
      "group": 1,
      "period": 6,
      "density": 1.93,
      "ionization_energy": 375.7,
      "electron_configuration": "[Xe] 6s1",
      "uses": "Used in atomic clocks, photoelectric cells, and drilling fluids in the oil industry.",
      "picture": "cesium.jpg"
    },
    {
      "name": "Francium",
      "symbol": "Fr",
      "atomic_number": 87,
      "atomic_mass": 223.02,
      "summary": "Francium is a highly radioactive alkali metal. It is extremely rare in nature due to its short half-life.",
      "founded_by": "Marguerite Catherine Perey",
      "state_of_matter": "Solid",
      "melting_point": "N/A",
      "group": 1,
      "period": 7,
      "density": "NA",
      "ionization_energy": "NA",
      "electron_configuration": "[Rn] 7s1",
      "uses": "Used in research and nuclear physics due to its radioactivity.",
      "picture": "francium.jpg"
    }
    
  ],
    "alkaline_earth_metals": [
    {
      "name": "Beryllium",
      "symbol": "Be",
      "atomic_number": 4,
      "atomic_mass": 9.0122,
      "summary": "Beryllium is a hard, brittle, gray-white metal. It is toxic and has high thermal conductivity.",
      "founded_by": "Louis-Nicolas Vauquelin",
      "state_of_matter": "Solid",
      "melting_point": 1560.15,
      "group": 2,
      "period": 2,
      "density": 1.85,
      "ionization_energy": 899.5,
      "electron_configuration": "[He] 2s2",
      "uses": "Used in aerospace and defense industries, as well as in X-ray machines due to its low absorption of X-rays.",
      "picture": "beryllium.jpg"
    },
    {
      "name": "Magnesium",
      "symbol": "Mg",
      "atomic_number": 12,
      "atomic_mass": 24.305,
      "summary": "Magnesium is a light, silvery-white metal. It is essential for biological processes and widely used in alloys.",
      "founded_by": "Sir Humphry Davy",
      "state_of_matter": "Solid",
      "melting_point": 923.15,
      "group": 2,
      "period": 3,
      "density": 1.738,
      "ionization_energy": 737.7,
      "electron_configuration": "[Ne] 3s2",
      "uses": "Used in lightweight alloys, fireworks, and as a dietary supplement in medicine.",
      "picture": "magnesium.jpg"
    },
    {
      "name": "Calcium",
      "symbol": "Ca",
      "atomic_number": 20,
      "atomic_mass": 40.078,
      "summary": "Calcium is a soft, gray, alkaline earth metal. It is essential for bones and teeth in living organisms.",
      "founded_by": "Humphry Davy",
      "state_of_matter": "Solid",
      "melting_point": 1115.15,
      "group": 2,
      "period": 4,
      "density": 1.54,
      "ionization_energy": 589.8,
      "electron_configuration": "[Ar] 4s2",
      "uses": "Used in construction, as a dietary supplement, and in the production of metals.",
      "picture": "calcium.jpg"
    },
    {
      "name": "Strontium",
      "symbol": "Sr",
      "atomic_number": 38,
      "atomic_mass": 87.62,
      "summary": "Strontium is a soft, silvery-white metal. It is used in fireworks to produce red colors.",
      "founded_by": "Adair Crawford",
      "state_of_matter": "Solid",
      "melting_point": 1042.15,
      "group": 2,
      "period": 5,
      "density": 2.64,
      "ionization_energy": 549.5,
      "electron_configuration": "[Kr] 5s2",
      "uses": "Used in pyrotechnics (fireworks), in cathode ray tubes, and as a radioactive tracer in medicine.",
      "picture": "strontium.jpg"
    },
    {
      "name": "Barium",
      "symbol": "Ba",
      "atomic_number": 56,
      "atomic_mass": 137.33,
      "summary": "Barium is a soft, silvery-white metal. It is used in drilling fluids in the oil industry and in X-ray imaging.",
      "founded_by": "Carl Wilhelm Scheele",
      "state_of_matter": "Solid",
      "melting_point": 1000.15,
      "group": 2,
      "period": 6,
      "density": 3.51,
      "ionization_energy": 502.9,
      "electron_configuration": "[Xe] 6s2",
      "uses": "Used in medical imaging (barium sulfate), in fireworks, and in the production of alloys.",
      "picture": "barium.jpg"
    },
    {
      "name": "Radium",
      "symbol": "Ra",
      "atomic_number": 88,
      "atomic_mass": 226.03,
      "summary": "Radium is a highly radioactive alkaline earth metal. It glows in the dark due to its radioactivity.",
      "founded_by": "Marie Skłodowska Curie and Pierre Curie",
      "state_of_matter": "Solid",
      "melting_point": 973.15,
      "group": 2,
      "period": 7,
      "density": 5.5,
      "ionization_energy": 509.3,
      "electron_configuration": "[Rn] 7s2",
      "uses": "Used in early medical treatments, but its use has been largely discontinued due to its radiation hazards.",
      "picture": "radium.jpg"
    }
    
  ],
    "transition_metals": [
    {
      "name": "Scandium",
      "symbol": "Sc",
      "atomic_number": 21,
      "atomic_mass": 44.956,
      "summary": "Scandium is a silvery-white, lightweight metal. It is used in aerospace and high-intensity lamps.",
      "founded_by": "Lars Fredrik Nilson",
      "state_of_matter": "Solid",
      "melting_point": 1814.15,
      "group": 3,
      "period": 4,
      "density": 2.99,
      "ionization_energy": 633.1,
      "electron_configuration": "[Ar] 3d1 4s2",
      "uses": "Used in aluminum-scandium alloys for aerospace applications and in certain high-intensity lamps.",
      "picture": "scandium.jpg"
    },
    {
      "name": "Titanium",
      "symbol": "Ti",
      "atomic_number": 22,
      "atomic_mass": 47.867,
      "summary": "Titanium is a strong, lightweight metal with excellent corrosion resistance. It is widely used in aerospace and medical implants.",
      "founded_by": "William Gregor",
      "state_of_matter": "Solid",
      "melting_point": 1941.15,
      "group": 4,
      "period": 4,
      "density": 4.54,
      "ionization_energy": 658.8,
      "electron_configuration": "[Ar] 3d2 4s2",
      "uses": "Used in aircraft, medical implants, jewelry, and various industrial applications.",
      "picture": "titanium.jpg"
    },
    {
      "name": "Vanadium",
      "symbol": "V",
      "atomic_number": 23,
      "atomic_mass": 50.942,
      "summary": "Vanadium is a hard, silvery-gray metal. It is used in steel production and as a catalyst in chemical reactions.",
      "founded_by": "Andrés Manuel del Río",
      "state_of_matter": "Solid",
      "melting_point": 2183.15,
      "group": 5,
      "period": 4,
      "density": 6.11,
      "ionization_energy": 650.9,
      "electron_configuration": "[Ar] 3d3 4s2",
      "uses": "Used in steel alloys, as a catalyst in chemical reactions, and in some vanadium redox batteries.",
      "picture": "vanadium.jpg"
    },
    {
      "name": "Chromium",
      "symbol": "Cr",
      "atomic_number": 24,
      "atomic_mass": 51.996,
      "summary": "Chromium is a hard, shiny metal known for its corrosion resistance. It is used in stainless steel and chrome plating.",
      "founded_by": "Louis Nicolas Vauquelin",
      "state_of_matter": "Solid",
      "melting_point": 2180.15,
      "group": 6,
      "period": 4,
      "density": 7.15,
      "ionization_energy": 653.8,
      "electron_configuration": "[Ar] 3d5 4s1",
      "uses": "Used in stainless steel, chrome plating, and in various alloys for its hardness and corrosion resistance.",
      "picture": "chromium.jpg"
    },
    {
      "name": "Manganese",
      "symbol": "Mn",
      "atomic_number": 25,
      "atomic_mass": 54.938,
      "summary": "Manganese is a gray-white, hard metal. It is used in steel production and as a trace nutrient for living organisms.",
      "founded_by": "Johan Gottlieb Gahn and Carl Wilhelm Scheele",
      "state_of_matter": "Solid",
      "melting_point": 1519.15,
      "group": 7,
      "period": 4,
      "density": 7.43,
      "ionization_energy": 717.3,
      "electron_configuration": "[Ar] 3d5 4s2",
      "uses": "Used in steelmaking, batteries, and as a trace nutrient in the human diet.",
      "picture": "manganese.jpg"
    },
    {
      "name": "Iron",
      "symbol": "Fe",
      "atomic_number": 26,
      "atomic_mass": 55.845,
      "summary": "Iron is a strong, ductile metal. It is the most commonly used metal in the world, primarily in construction and manufacturing.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 1811.15,
      "group": 8,
      "period": 4,
      "density": 7.87,
      "ionization_energy": 762.5,
      "electron_configuration": "[Ar] 3d6 4s2",
      "uses": "Used in construction, manufacturing, and as a key component in steel and other alloys.",
      "picture": "iron.jpg"
    },
    {
      "name": "Cobalt",
      "symbol": "Co",
      "atomic_number": 27,
      "atomic_mass": 58.933,
      "summary": "Cobalt is a hard, silvery-blue metal. It is used in alloys, batteries, and as a pigment in ceramics and glass.",
      "founded_by": "George Brandt",
      "state_of_matter": "Solid",
      "melting_point": 1768.15,
      "group": 9,
      "period": 4,
      "density": 8.9,
      "ionization_energy": 760.4,
      "electron_configuration": "[Ar] 3d7 4s2",
      "uses": "Used in alloys for aircraft engines, in batteries, and as a coloring agent in ceramics and glass.",
      "picture": "cobalt.jpg"
    },
    {
      "name": "Nickel",
      "symbol": "Ni",
      "atomic_number": 28,
      "atomic_mass": 58.693,
      "summary": "Nickel is a silvery-white metal known for its resistance to corrosion. It is used in alloys and coinage.",
      "founded_by": "Axel Fredrik Cronstedt",
      "state_of_matter": "Solid",
      "melting_point": 1728.15,
      "group": 10,
      "period": 4,
      "density": 8.9,
      "ionization_energy": 737.1,
      "electron_configuration": "[Ar] 3d8 4s2",
      "uses": "Used in stainless steel, coins, and various alloys for its corrosion resistance and strength.",
      "picture": "nickel.jpg"
    },
    {
      "name": "Copper",
      "symbol": "Cu",
      "atomic_number": 29,
      "atomic_mass": 63.546,
      "summary": "Copper is a reddish-brown metal. It is known for its excellent electrical conductivity and malleability.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 1357.75,
      "group": 11,
      "period": 4,
      "density": 8.96,
      "ionization_energy": 745.5,
      "electron_configuration": "[Ar] 3d10 4s1",
      "uses": "Used in electrical wiring, plumbing, and in various alloys for its electrical and thermal conductivity.",
      "picture": "copper.jpg"
    },
    {
      "name": "Zinc",
      "symbol": "Zn",
      "atomic_number": 30,
      "atomic_mass": 65.38,
      "summary": "Zinc is a bluish-white metal. It is used in galvanization, as a dietary supplement, and in batteries.",
      "founded_by": "Alchemists",
      "state_of_matter": "Solid",
      "melting_point": 692.68,
      "group": 12,
      "period": 4,
      "density": 7.13,
      "ionization_energy": 906.4,
      "electron_configuration": "[Ar] 3d10 4s2",
      "uses": "Used in galvanization to protect iron and steel from corrosion, as a dietary supplement, and in batteries.",
      "picture": "zinc.jpg"
    },
    {
      "name": "Yttrium",
      "symbol": "Y",
      "atomic_number": 39,
      "atomic_mass": 88.906,
      "summary": "Yttrium is a silvery-metallic element. It is used in the production of phosphors for color television tubes.",
      "founded_by": "Johan Gadolin",
      "state_of_matter": "Solid",
      "melting_point": 1799.15,
      "group": 3,
      "period": 5,
      "density": 4.47,
      "ionization_energy": 600.0,
      "electron_configuration": "[Kr] 4d1 5s2",
      "uses": "Used in phosphors for color television tubes and as an alloying element in some steels.",
      "picture": "yttrium.jpg"
    },
    {
      "name": "Zirconium",
      "symbol": "Zr",
      "atomic_number": 40,
      "atomic_mass": 91.224,
      "summary": "Zirconium is a silvery-gray, lustrous metal. It is used in nuclear reactors, ceramics, and as a corrosion-resistant alloy.",
      "founded_by": "Martin Heinrich Klaproth",
      "state_of_matter": "Solid",
      "melting_point": 2125.15,
      "group": 4,
      "period": 5,
      "density": 6.52,
      "ionization_energy": 640.1,
      "electron_configuration": "[Kr] 4d2 5s2",
      "uses": "Used in nuclear reactors, as a corrosion-resistant alloy, and in ceramics.",
      "picture": "zirconium.jpg"
    },
    {
      "name": "Niobium",
      "symbol": "Nb",
      "atomic_number": 41,
      "atomic_mass": 92.906,
      "summary": "Niobium is a soft, gray, ductile metal. It is used in superconductors, alloys, and in the aerospace industry.",
      "founded_by": "Charles Hatchett",
      "state_of_matter": "Solid",
      "melting_point": 2750.15,
      "group": 5,
      "period": 5,
      "density": 8.57,
      "ionization_energy": 652.1,
      "electron_configuration": "[Kr] 4d4 5s1",
      "uses": "Used in superconducting materials, high-strength alloys, and in the aerospace industry.",
      "picture": "niobium.jpg"
    },
    {
      "name": "Molybdenum",
      "symbol": "Mo",
      "atomic_number": 42,
      "atomic_mass": 95.95,
      "summary": "Molybdenum is a silvery-white, hard metal. It is used in steel alloys and as a catalyst in the chemical industry.",
      "founded_by": "Carl Wilhelm Scheele and Peter Jacob Hjelm",
      "state_of_matter": "Solid",
      "melting_point": 2896.15,
      "group": 6,
      "period": 5,
      "density": 10.22,
      "ionization_energy": 684.3,
      "electron_configuration": "[Kr] 4d5 5s1",
      "uses": "Used in steel alloys, as a catalyst in the chemical industry, and in electronic and electrical applications.",
      "picture": "molybdenum.jpg"
    },
    {
      "name": "Technetium",
      "symbol": "Tc",
      "atomic_number": 43,
      "atomic_mass": 98.0,
      "summary": "Technetium is a radioactive element. It is used in nuclear medicine for imaging and research purposes.",
      "founded_by": "Carlo Perrier and Emilio Segrè",
      "state_of_matter": "Solid",
      "melting_point": 2430.15,
      "group": 7,
      "period": 5,
      "density": 11.5,
      "ionization_energy": 702.0,
      "electron_configuration": "[Kr] 4d5 5s2",
      "uses": "Used in nuclear medicine for imaging and research due to its radioactivity.",
      "picture": "technetium.jpg"
    },
    {
      "name": "Ruthenium",
      "symbol": "Ru",
      "atomic_number": 44,
      "atomic_mass": 101.07,
      "summary": "Ruthenium is a hard, silvery-white metal. It is used in electronics, jewelry, and in catalytic converters.",
      "founded_by": "Karl Ernst Claus",
      "state_of_matter": "Solid",
      "melting_point": 2607.15,
      "group": 8,
      "period": 5,
      "density": 12.4,
      "ionization_energy": 710.2,
      "electron_configuration": "[Kr] 4d7 5s1",
      "uses": "Used in electrical contacts, electronics, jewelry, and as a catalyst in catalytic converters.",
      "picture": "ruthenium.jpg"
    },
    {
      "name": "Rhodium",
      "symbol": "Rh",
      "atomic_number": 45,
      "atomic_mass": 102.91,
      "summary": "Rhodium is a rare, silvery-white metal. It is used in catalytic converters, electrical contacts, and for decorative plating.",
      "founded_by": "William Hyde Wollaston",
      "state_of_matter": "Solid",
      "melting_point": 2239.15,
      "group": 9,
      "period": 5,
      "density": 12.4,
      "ionization_energy": 719.7,
      "electron_configuration": "[Kr] 4d8 5s1",
      "uses": "Used in catalytic converters, electrical contacts, and for decorative plating of jewelry and silverware.",
      "picture": "rhodium.jpg"
    },
    {
      "name": "Palladium",
      "symbol": "Pd",
      "atomic_number": 46,
      "atomic_mass": 106.42,
      "summary": "Palladium is a rare, silvery-white metal. It is used in catalytic converters, jewelry, and in the electronics industry.",
      "founded_by": "William Hyde Wollaston",
      "state_of_matter": "Solid",
      "melting_point": 1828.05,
      "group": 10,
      "period": 5,
      "density": 12.0,
      "ionization_energy": 804.4,
      "electron_configuration": "[Kr] 4d10",
      "uses": "Used in catalytic converters, jewelry making, and in various electronic components.",
      "picture": "palladium.jpg"
    },
    {
      "name": "Silver",
      "symbol": "Ag",
      "atomic_number": 47,
      "atomic_mass": 107.87,
      "summary": "Silver is a shiny, white metal. It is used in jewelry, coins, photography, and for its antibacterial properties.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 1234.15,
      "group": 11,
      "period": 5,
      "density": 10.49,
      "ionization_energy": 731.0,
      "electron_configuration": "[Kr] 4d10 5s1",
      "uses": "Used in jewelry, coins, photography, and in medical applications for its antibacterial properties.",
      "picture": "silver.jpg"
    },
    {
      "name": "Cadmium",
      "symbol": "Cd",
      "atomic_number": 48,
      "atomic_mass": 112.41,
      "summary": "Cadmium is a soft, bluish-white metal. It is used in batteries, pigments, and as a corrosion-resistant plating.",
      "founded_by": "Friedrich Stromeyer",
      "state_of_matter": "Solid",
      "melting_point": 594.22,
      "group": 12,
      "period": 5,
      "density": 8.65,
      "ionization_energy": 868.0,
      "electron_configuration": "[Kr] 4d10 5s2",
      "uses": "Used in rechargeable batteries, pigments, and as a corrosion-resistant plating.",
      "picture": "cadmium.jpg"
    },
    {
      "name": "Hafnium",
      "symbol": "Hf",
      "atomic_number": 72,
      "atomic_mass": 178.49,
      "summary": "Hafnium is a silvery-gray metal. It is used in nuclear reactors and as a component in high-temperature alloys.",
      "founded_by": "Dirk Coster and George de Hevesy",
      "state_of_matter": "Solid",
      "melting_point": 2500.15,
      "group": 4,
      "period": 6,
      "density": 13.31,
      "ionization_energy": 658.5,
      "electron_configuration": "[Xe] 4f14 5d2 6s2",
      "uses": "Used in nuclear reactors, in high-temperature alloys, and in certain electrical applications.",
      "picture": "hafnium.jpg"
    },
    {
      "name": "Tantalum",
      "symbol": "Ta",
      "atomic_number": 73,
      "atomic_mass": 180.95,
      "summary": "Tantalum is a rare, blue-gray metal. It is used in electronic components, as a capacitor material, and in medical implants.",
      "founded_by": "Anders Gustaf Ekeberg",
      "state_of_matter": "Solid",
      "melting_point": 3290.15,
      "group": 5,
      "period": 6,
      "density": 16.65,
      "ionization_energy": 761.0,
      "electron_configuration": "[Xe] 4f14 5d3 6s2",
      "uses": "Used in electronic components, as a capacitor material, and in medical implants.",
      "picture": "tantalum.jpg"
    },
    {
      "name": "Tungsten",
      "symbol": "W",
      "atomic_number": 74,
      "atomic_mass": 183.84,
      "summary": "Tungsten is a hard, dense metal with the highest melting point of all elements. It is used in electrical wires and filaments.",
      "founded_by": "Carl Wilhelm Scheele",
      "state_of_matter": "Solid",
      "melting_point": 3695.15,
      "group": 6,
      "period": 6,
      "density": 19.25,
      "ionization_energy": 770.0,
      "electron_configuration": "[Xe] 4f14 5d4 6s2",
      "uses": "Used in electrical wires, filaments, and in the aerospace and defense industries.",
      "picture": "tungsten.jpg"
    },
    {
      "name": "Rhenium",
      "symbol": "Re",
      "atomic_number": 75,
      "atomic_mass": 186.21,
      "summary": "Rhenium is a silvery-gray metal. It is used in high-temperature superalloys, electrical contacts, and as a catalyst.",
      "founded_by": "Masataka Ogawa",
      "state_of_matter": "Solid",
      "melting_point": 3459.15,
      "group": 7,
      "period": 6,
      "density": 21.02,
      "ionization_energy": 760.0,
      "electron_configuration": "[Xe] 4f14 5d5 6s2",
      "uses": "Used in high-temperature superalloys, electrical contacts, and as a catalyst in various reactions.",
      "picture": "rhenium.jpg"
    },
    {
      "name": "Osmium",
      "symbol": "Os",
      "atomic_number": 76,
      "atomic_mass": 190.23,
      "summary": "Osmium is a dense, bluish-white metal. It is used in electrical contacts and in the manufacture of fountain pen tips.",
      "founded_by": "Smithson Tennant",
      "state_of_matter": "Solid",
      "melting_point": 3306.15,
      "group": 8,
      "period": 6,
      "density": 22.59,
      "ionization_energy": 840.0,
      "electron_configuration": "[Xe] 4f14 5d6 6s2",
      "uses": "Used in electrical contacts and in the manufacture of fountain pen tips.",
      "picture": "osmium.jpg"
    },
    {
      "name": "Iridium",
      "symbol": "Ir",
      "atomic_number": 77,
      "atomic_mass": 192.22,
      "summary": "Iridium is a dense, corrosion-resistant metal. It is used in spark plugs, electrical contacts, and in jewelry.",
      "founded_by": "Smithson Tennant",
      "state_of_matter": "Solid",
      "melting_point": 2716.15,
      "group": 9,
      "period": 6,
      "density": 22.56,
      "ionization_energy": 880.0,
      "electron_configuration": "[Xe] 4f14 5d7 6s2",
      "uses": "Used in spark plugs, electrical contacts, and in making extremely durable jewelry.",
      "picture": "iridium.jpg"
    },
    {
      "name": "Platinum",
      "symbol": "Pt",
      "atomic_number": 78,
      "atomic_mass": 195.08,
      "summary": "Platinum is a dense, silvery-white metal. It is used in jewelry, catalytic converters, and in the chemical industry.",
      "founded_by": "Antonio de Ulloa",
      "state_of_matter": "Solid",
      "melting_point": 2041.15,
      "group": 10,
      "period": 6,
      "density": 21.46,
      "ionization_energy": 870.0,
      "electron_configuration": "[Xe] 4f14 5d9 6s1",
      "uses": "Used in jewelry, catalytic converters, and in various chemical applications as a catalyst.",
      "picture": "platinum.jpg"
    },
    {
      "name": "Gold",
      "symbol": "Au",
      "atomic_number": 79,
      "atomic_mass": 196.97,
      "summary": "Gold is a precious, yellow metal. It is used in jewelry, currency, and in various electronic components.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 1337.33,
      "group": 11,
      "period": 6,
      "density": 19.32,
      "ionization_energy": 890.1,
      "electron_configuration": "[Xe] 4f14 5d10 6s1",
      "uses": "Used in jewelry, coins, electronic connectors, and as a symbol of wealth and status.",
      "picture": "gold.jpg"
    },
    {
      "name": "Mercury",
      "symbol": "Hg",
      "atomic_number": 80,
      "atomic_mass": 200.59,
      "summary": "Mercury is a liquid metal at room temperature. It is used in thermometers, barometers, and electrical switches.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Liquid",
      "melting_point": 234.32,
      "group": 12,
      "period": 6,
      "density": 13.53,
      "ionization_energy": 1007.1,
      "electron_configuration": "[Xe] 4f14 5d10 6s2",
      "uses": "Used in thermometers, barometers, electrical switches, and historically in dental amalgam.",
      "picture": "mercury.jpg"
    },
    {
      "name": "Rutherfordium",
      "symbol": "Rf",
      "atomic_number": 104,
      "atomic_mass": 267.12,
      "summary": "Rutherfordium is a synthetic element. It has no known uses and is primarily produced for research purposes.",
      "founded_by": "Joint Institute for Nuclear Research (JINR) and Lawrence Livermore National Laboratory (LLNL)",
      "state_of_matter": "Unknown",
      "melting_point": "Unknown",
      "group": 4,
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d2 7s2",
      "uses": "Primarily produced for scientific research purposes.",
      "picture": "rutherfordium.jpg"
    },
    {
      "name": "Dubnium",
      "symbol": "Db",
      "atomic_number": 105,
      "atomic_mass": 268.13,
      "summary": "Dubnium is a synthetic element. It has no known uses and is primarily produced for research purposes.",
      "founded_by": "Joint Institute for Nuclear Research (JINR)",
      "state_of_matter": "Unknown",
      "melting_point": "Unknown",
      "group": 5,
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d3 7s2",
      "uses": "Primarily produced for scientific research purposes.",
      "picture": "dubnium.jpg"
    },
    {
      "name": "Seaborgium",
      "symbol": "Sg",
      "atomic_number": 106,
      "atomic_mass": 271.13,
      "summary": "Seaborgium is a synthetic element. It has no known uses and is primarily produced for research purposes.",
      "founded_by": "Joint Institute for Nuclear Research (JINR) and Lawrence Livermore National Laboratory (LLNL)",
      "state_of_matter": "Unknown",
      "melting_point": "Unknown",
      "group": 6,
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d4 7s2",
      "uses": "Primarily produced for scientific research purposes.",
      "picture": "seaborgium.jpg"
    },
    {
      "name": "Bohrium",
      "symbol": "Bh",
      "atomic_number": 107,
      "atomic_mass": 270,
      "summary": "Bohrium is a synthetic element. It has no known uses and is primarily produced for research purposes.",
      "founded_by": "Gesellschaft für Schwerionenforschung (GSI)",
      "state_of_matter": "Unknown",
      "melting_point": "Unknown",
      "group": 7,
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d5 7s2",
      "uses": "Primarily produced for scientific research purposes.",
      "picture": "bohrium.jpg"
    },
    {
      "name": "Hassium",
      "symbol": "Hs",
      "atomic_number": 108,
      "atomic_mass": 277,
      "summary": "Hassium is a synthetic element. It has no known uses and is primarily produced for research purposes.",
      "founded_by": "Gesellschaft für Schwerionenforschung (GSI)",
      "state_of_matter": "Unknown",
      "melting_point": "Unknown",
      "group": 8,
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d6 7s2",
      "uses": "Primarily produced for scientific research purposes.",
      "picture": "hassium.jpg"
    }
  ],
    "post_transition_metals": [
    {
      "name": "Aluminum",
      "symbol": "Al",
      "atomic_number": 13,
      "atomic_mass": 26.982,
      "summary": "Aluminum is a lightweight, silvery-white metal known for its corrosion resistance. It is used in various industries.",
      "founded_by": "Hans Christian Ørsted",
      "state_of_matter": "Solid",
      "melting_point": 933.47,
      "group": 13,
      "period": 3,
      "density": 2.7,
      "ionization_energy": 577.5,
      "electron_configuration": "[Ne] 3s2 3p1",
      "uses": "Used in construction, transportation, packaging, and electrical wiring.",
      "picture": "aluminum.jpg"
    },
    {
      "name": "Gallium",
      "symbol": "Ga",
      "atomic_number": 31,
      "atomic_mass": 69.723,
      "summary": "Gallium is a soft, silvery metal. It is used in semiconductors and as a component in some high-temperature alloys.",
      "founded_by": "Lecoq de Boisbaudran",
      "state_of_matter": "Solid",
      "melting_point": 302.91,
      "group": 13,
      "period": 4,
      "density": 5.91,
      "ionization_energy": 578.8,
      "electron_configuration": "[Ar] 3d10 4s2 4p1",
      "uses": "Used in semiconductors, LEDs, and in the preparation of certain high-temperature alloys.",
      "picture": "gallium.jpg"
    },
    {
      "name": "Indium",
      "symbol": "In",
      "atomic_number": 49,
      "atomic_mass": 114.82,
      "summary": "Indium is a soft, silvery metal. It is used in semiconductors, low-melting-point alloys, and in the production of transparent conductive coatings.",
      "founded_by": "Ferdinand Reich and Hieronymous Theodor Richter",
      "state_of_matter": "Solid",
      "melting_point": 429.75,
      "group": 13,
      "period": 5,
      "density": 7.31,
      "ionization_energy": 558.3,
      "electron_configuration": "[Kr] 4d10 5s2 5p1",
      "uses": "Used in semiconductors, low-melting-point alloys, and in the production of transparent conductive coatings.",
      "picture": "indium.jpg"
    },
    {
      "name": "Thallium",
      "symbol": "Tl",
      "atomic_number": 81,
      "atomic_mass": 204.38,
      "summary": "Thallium is a soft, bluish-white metal. It is used in electronic components and as a contrast agent in medical imaging.",
      "founded_by": "Sir William Crookes",
      "state_of_matter": "Solid",
      "melting_point": 577.15,
      "group": 13,
      "period": 6,
      "density": 11.85,
      "ionization_energy": 589.4,
      "electron_configuration": "[Xe] 4f14 5d10 6s2 6p1",
      "uses": "Used in electronic components and as a contrast agent in medical imaging.",
      "picture": "thallium.jpg"
    },
    {
      "name": "Tin",
      "symbol": "Sn",
      "atomic_number": 50,
      "atomic_mass": 118.71,
      "summary": "Tin is a silvery-white metal. It is used in alloys, solder, and as a protective coating for other metals.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 505.08,
      "group": 14,
      "period": 5,
      "density": 7.29,
      "ionization_energy": 708.6,
      "electron_configuration": "[Kr] 4d10 5s2 5p2",
      "uses": "Used in solder, tinplate, and various alloys, as well as in the production of protective coatings.",
      "picture": "tin.jpg"
    },
    {
      "name": "Lead",
      "symbol": "Pb",
      "atomic_number": 82,
      "atomic_mass": 207.2,
      "summary": "Lead is a dense, bluish-gray metal. It is used in batteries, radiation shielding, and in various alloys.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 600.65,
      "group": 14,
      "period": 6,
      "density": 11.34,
      "ionization_energy": 715.6,
      "electron_configuration": "[Xe] 4f14 5d10 6s2 6p2",
      "uses": "Used in batteries, radiation shielding, and in the production of various alloys.",
      "picture": "lead.jpg"
    },
    {
      "name": "Bismuth",
      "symbol": "Bi",
      "atomic_number": 83,
      "atomic_mass": 208.98,
      "summary": "Bismuth is a brittle, pinkish-white metal. It is used in cosmetics, pharmaceuticals, and as a replacement for lead in some applications.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 544.59,
      "group": 15,
      "period": 6,
      "density": 9.78,
      "ionization_energy": 703.0,
      "electron_configuration": "[Xe] 4f14 5d10 6s2 6p3",
      "uses": "Used in cosmetics, pharmaceuticals, and as a replacement for lead in certain applications.",
      "picture": "bismuth.jpg"
    },
    {
      "name": "Polonium",
      "symbol": "Po",
      "atomic_number": 84,
      "atomic_mass": 209.98,
      "summary": "Polonium is a radioactive element. It is used in static eliminators and as a heat source in nuclear power devices.",
      "founded_by": "Marie Curie and Pierre Curie",
      "state_of_matter": "Solid",
      "melting_point": 527.15,
      "group": 16,
      "period": 6,
      "density": 9.20,
      "ionization_energy": 812.1,
      "electron_configuration": "[Xe] 4f14 5d10 6s2 6p4",
      "uses": "Used in static eliminators and as a heat source in nuclear power devices.",
      "picture": "polonium.jpg"
    },
    {
      "name": "Astatine",
      "symbol": "At",
      "atomic_number": 85,
      "atomic_mass": 210.0,
      "summary": "Astatine is a rare and highly radioactive element. It has limited practical uses due to its scarcity and radioactivity.",
      "founded_by": "Dale R. Corson, Kenneth Ross MacKenzie, and Emilio Segrè",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": 17,
      "period": 6,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Xe] 4f14 5d10 6s2 6p5",
      "uses": "Limited practical uses due to its scarcity and radioactivity.",
      "picture": "astatine.jpg"
    }
  ],

    "metalloids": [
    {
      "name": "Boron",
      "symbol": "B",
      "atomic_number": 5,
      "atomic_mass": 10.81,
      "summary": "Boron is a non-metallic element. It is used in the manufacture of glass, ceramics, and as a neutron absorber in nuclear reactors.",
      "founded_by": "Sir Humphry Davy",
      "state_of_matter": "Solid",
      "melting_point": 2349.15,
      "group": 13,
      "period": 2,
      "density": 2.34,
      "ionization_energy": 800.6,
      "electron_configuration": "1s2 2s2 2p1",
      "uses": "Used in glass and ceramics production, as a neutron absorber in nuclear reactors, and in various compounds.",
      "picture": "boron.jpg"
    },
    {
      "name": "Silicon",
      "symbol": "Si",
      "atomic_number": 14,
      "atomic_mass": 28.09,
      "summary": "Silicon is a vital component of semiconductors and solar cells. It is used in electronics and as a building material.",
      "founded_by": "Jöns Jacob Berzelius",
      "state_of_matter": "Solid",
      "melting_point": 1687.15,
      "group": 14,
      "period": 3,
      "density": 2.33,
      "ionization_energy": 786.5,
      "electron_configuration": "1s2 2s2 2p6 3s2 3p2",
      "uses": "Used in semiconductors, solar cells, glass production, and as a building material.",
      "picture": "silicon.jpg"
    },
    {
      "name": "Germanium",
      "symbol": "Ge",
      "atomic_number": 32,
      "atomic_mass": 72.63,
      "summary": "Germanium is used in semiconductors and optical fibers. It has some electronic applications.",
      "founded_by": "Clemens Winkler",
      "state_of_matter": "Solid",
      "melting_point": 1211.15,
      "group": 14,
      "period": 4,
      "density": 5.32,
      "ionization_energy": 762.1,
      "electron_configuration": "[Ar] 3d10 4s2 4p2",
      "uses": "Used in semiconductors, optical fibers, and in certain electronic devices.",
      "picture": "germanium.jpg"
    },
    {
      "name": "Arsenic",
      "symbol": "As",
      "atomic_number": 33,
      "atomic_mass": 74.92,
      "summary": "Arsenic is a poisonous metalloid. It has limited practical uses but has been used historically in various applications.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 1090.15,
      "group": 15,
      "period": 4,
      "density": 5.72,
      "ionization_energy": 947.0,
      "electron_configuration": "[Ar] 3d10 4s2 4p3",
      "uses": "Historically used in various applications, but limited practical uses due to its toxicity.",
      "picture": "arsenic.jpg"
    },
    {
      "name": "Antimony",
      "symbol": "Sb",
      "atomic_number": 51,
      "atomic_mass": 121.76,
      "summary": "Antimony is used in flame retardants, batteries, and some alloys. It has been used historically in medicine.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 903.78,
      "group": 15,
      "period": 5,
      "density": 6.68,
      "ionization_energy": 834.0,
      "electron_configuration": "[Kr] 4d10 5s2 5p3",
      "uses": "Used in flame retardants, batteries, some alloys, and historically in medicine.",
      "picture": "antimony.jpg"
    },
    {
      "name": "Tellurium",
      "symbol": "Te",
      "atomic_number": 52,
      "atomic_mass": 127.6,
      "summary": "Tellurium is used in alloys, solar cells, and as a component in certain electronic devices.",
      "founded_by": "Franz-Joseph Müller von Reichenstein",
      "state_of_matter": "Solid",
      "melting_point": 722.66,
      "group": 16,
      "period": 5,
      "density": 6.24,
      "ionization_energy": 869.3,
      "electron_configuration": "[Kr] 4d10 5s2 5p4",
      "uses": "Used in alloys, solar cells, and in certain electronic devices.",
      "picture": "tellurium.jpg"
    }
  ],

    "reactive_nonmetals": [
    {
      "name": "Hydrogen",
      "symbol": "H",
      "atomic_number": 1,
      "atomic_mass": 1.01,
      "summary": "Hydrogen is the lightest and most abundant element in the universe. It is a colorless, odorless gas.",
      "founded_by": "Henry Cavendish",
      "state_of_matter": "Gas",
      "melting_point": 13.99,
      "group": 1,
      "period": 1,
      "density": 0.00009,
      "ionization_energy": 1312.0,
      "electron_configuration": "1s1",
      "uses": "Used in the production of ammonia, as a fuel for rockets and vehicles, and in various industrial processes.",
      "picture": "hydrogen.jpg"
    },
    {
      "name": "Carbon",
      "symbol": "C",
      "atomic_number": 6,
      "atomic_mass": 12.01,
      "summary": "Carbon is the basis of organic chemistry. It exists in various forms, including diamond and graphite.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 3915.15,
      "group": 14,
      "period": 2,
      "density": 2.26,
      "ionization_energy": 1086.5,
      "electron_configuration": "1s2 2s2 2p2",
      "uses": "Used in the production of carbon compounds, as fuel (e.g., coal), and in various industrial applications.",
      "picture": "carbon.jpg"
    },
    {
      "name": "Nitrogen",
      "symbol": "N",
      "atomic_number": 7,
      "atomic_mass": 14.01,
      "summary": "Nitrogen is a colorless, odorless gas. It is essential for life and is a key component of proteins and nucleic acids.",
      "founded_by": "Daniel Rutherford",
      "state_of_matter": "Gas",
      "melting_point": 63.15,
      "group": 15,
      "period": 2,
      "density": 0.00125,
      "ionization_energy": 1402.3,
      "electron_configuration": "1s2 2s2 2p3",
      "uses": "Used in the food industry for packaging and preservation, as a cooling agent, and in various industrial processes.",
      "picture": "nitrogen.jpg"
    },
    {
      "name": "Oxygen",
      "symbol": "O",
      "atomic_number": 8,
      "atomic_mass": 16.00,
      "summary": "Oxygen is essential for respiration and combustion. It is a colorless, odorless gas found in the Earth's atmosphere.",
      "founded_by": "Carl Wilhelm Scheele, Joseph Priestley, and Antoine Lavoisier",
      "state_of_matter": "Gas",
      "melting_point": 54.36,
      "group": 16,
      "period": 2,
      "density": 0.00143,
      "ionization_energy": 1313.9,
      "electron_configuration": "1s2 2s2 2p4",
      "uses": "Used in respiration by living organisms, combustion processes, and in various industrial applications.",
      "picture": "oxygen.jpg"
    },
    {
      "name": "Phosphorus",
      "symbol": "P",
      "atomic_number": 15,
      "atomic_mass": 30.97,
      "summary": "Phosphorus is essential for life and is a key component of DNA, RNA, and ATP. It exists in several forms, including white and red phosphorus.",
      "founded_by": "Hennig Brand",
      "state_of_matter": "Solid",
      "melting_point": 317.25,
      "group": 15,
      "period": 3,
      "density": 1.82,
      "ionization_energy": 1011.8,
      "electron_configuration": "[Ne] 3s2 3p3",
      "uses": "Used in fertilizers, detergents, and as a component in various chemical compounds.",
      "picture": "phosphorus.jpg"
    },
    {
      "name": "Sulfur",
      "symbol": "S",
      "atomic_number": 16,
      "atomic_mass": 32.07,
      "summary": "Sulfur is a non-metallic element. It is used in the production of sulfuric acid and as a component in various chemicals.",
      "founded_by": "Ancient civilizations",
      "state_of_matter": "Solid",
      "melting_point": 388.36,
      "group": 16,
      "period": 3,
      "density": 2.07,
      "ionization_energy": 999.6,
      "electron_configuration": "[Ne] 3s2 3p4",
      "uses": "Used in the production of sulfuric acid, in vulcanization of rubber, and in various chemical processes.",
      "picture": "sulfur.jpg"
    }
  ],

    "halogens": [
    {
      "name": "Fluorine",
      "symbol": "F",
      "atomic_number": 9,
      "atomic_mass": 18.99,
      "summary": "Fluorine is a highly reactive, pale yellow gas. It is the most electronegative element and forms compounds with various elements.",
      "founded_by": "Henri Moissan",
      "state_of_matter": "Gas",
      "melting_point": 53.53,
      "group": 17,
      "period": 2,
      "density": 0.0017,
      "ionization_energy": 1681.0,
      "electron_configuration": "1s2 2s2 2p5",
      "uses": "Used in toothpaste and water fluoridation, as well as in the production of various chemicals.",
      "picture": "fluorine.jpg"
    },
    {
      "name": "Chlorine",
      "symbol": "Cl",
      "atomic_number": 17,
      "atomic_mass": 35.45,
      "summary": "Chlorine is a greenish-yellow gas. It is used in water treatment, as a disinfectant, and in the production of chemicals.",
      "founded_by": "Carl Wilhelm Scheele",
      "state_of_matter": "Gas",
      "melting_point": 171.65,
      "group": 17,
      "period": 3,
      "density": 0.0032,
      "ionization_energy": 1251.2,
      "electron_configuration": "1s2 2s2 2p6 3s2 3p5",
      "uses": "Used in water treatment, as a disinfectant, and in the production of various chemicals and plastics.",
      "picture": "chlorine.jpg"
    },
    {
      "name": "Bromine",
      "symbol": "Br",
      "atomic_number": 35,
      "atomic_mass": 79.90,
      "summary": "Bromine is a dark red-brown liquid at room temperature. It is used in flame retardants and as a disinfectant.",
      "founded_by": "Antoine Jérôme Balard",
      "state_of_matter": "Liquid",
      "melting_point": 265.95,
      "group": 17,
      "period": 4,
      "density": 3.12,
      "ionization_energy": 1139.9,
      "electron_configuration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p5",
      "uses": "Used in flame retardants, as a disinfectant, and in the production of certain chemicals.",
      "picture": "bromine.jpg"
    },
    {
      "name": "Iodine",
      "symbol": "I",
      "atomic_number": 53,
      "atomic_mass": 126.90,
      "summary": "Iodine is a purple-black solid. It is used in medicine, as a disinfectant, and in the production of photographic chemicals.",
      "founded_by": "Bernard Courtois",
      "state_of_matter": "Solid",
      "melting_point": 386.85,
      "group": 17,
      "period": 5,
      "density": 4.94,
      "ionization_energy": 1008.4,
      "electron_configuration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p5",
      "uses": "Used in medicine, as a disinfectant, and in the production of photographic chemicals.",
      "picture": "iodine.jpg"
    },
    {
      "name": "Astatine",
      "symbol": "At",
      "atomic_number": 85,
      "atomic_mass": 210.0,
      "summary": "Astatine is a rare and highly radioactive element. It has limited practical uses due to its scarcity and radioactivity.",
      "founded_by": "Dale R. Corson, Kenneth Ross MacKenzie, and Emilio Segrè",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": 17,
      "period": 6,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Xe] 4f14 5d10 6s2 6p5",
      "uses": "Limited practical uses due to its scarcity and radioactivity.",
      "picture": "astatine.jpg"
    }
  ],

    "noble_gases": [
    {
      "name": "Helium",
      "symbol": "He",
      "atomic_number": 2,
      "atomic_mass": 4.00,
      "summary": "Helium is a colorless, odorless gas. It is the second-lightest and second-most abundant element in the universe.",
      "founded_by": "Pierre Janssen and Norman Lockyer",
      "state_of_matter": "Gas",
      "melting_point": 0.95,
      "group": 18,
      "period": 1,
      "density": 0.0001785,
      "ionization_energy": 2372.3,
      "electron_configuration": "1s2",
      "uses": "Used in cryogenics, as a coolant for MRI machines, and in balloons for buoyancy.",
      "picture": "helium.jpg"
    },
    {
      "name": "Neon",
      "symbol": "Ne",
      "atomic_number": 10,
      "atomic_mass": 20.18,
      "summary": "Neon is a colorless, inert gas. It is used in neon signs and as a component in certain types of lasers.",
      "founded_by": "Sir William Ramsay and Morris Travers",
      "state_of_matter": "Gas",
      "melting_point": 24.56,
      "group": 18,
      "period": 2,
      "density": 0.0008999,
      "ionization_energy": 2080.7,
      "electron_configuration": "1s2 2s2 2p6",
      "uses": "Used in neon signs, as a coolant in cryogenics, and in some types of lasers.",
      "picture": "neon.jpg"
    },
    {
      "name": "Argon",
      "symbol": "Ar",
      "atomic_number": 18,
      "atomic_mass": 39.95,
      "summary": "Argon is a colorless, inert gas. It is used in welding, as a shielding gas, and in some types of lighting.",
      "founded_by": "Sir William Ramsay and Lord Rayleigh",
      "state_of_matter": "Gas",
      "melting_point": 83.80,
      "group": 18,
      "period": 3,
      "density": 0.0017837,
      "ionization_energy": 1520.6,
      "electron_configuration": "1s2 2s2 2p6 3s2 3p6",
      "uses": "Used in welding, as a shielding gas, in some types of lighting, and as a preservative in historical documents.",
      "picture": "argon.jpg"
    },
    {
      "name": "Krypton",
      "symbol": "Kr",
      "atomic_number": 36,
      "atomic_mass": 83.80,
      "summary": "Krypton is a colorless, inert gas. It is used in some types of lighting, especially in high-intensity discharge lamps.",
      "founded_by": "Sir William Ramsay and Morris Travers",
      "state_of_matter": "Gas",
      "melting_point": 115.79,
      "group": 18,
      "period": 4,
      "density": 0.003733,
      "ionization_energy": 1350.8,
      "electron_configuration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6",
      "uses": "Used in high-intensity discharge lamps and other specialized lighting applications.",
      "picture": "krypton.jpg"
    },
    {
      "name": "Xenon",
      "symbol": "Xe",
      "atomic_number": 54,
      "atomic_mass": 131.29,
      "summary": "Xenon is a colorless, inert gas. It is used in lighting, as an anesthetic, and in various high-performance applications.",
      "founded_by": "Sir William Ramsay",
      "state_of_matter": "Gas",
      "melting_point": 161.36,
      "group": 18,
      "period": 5,
      "density": 0.005887,
      "ionization_energy": 1170.4,
      "electron_configuration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6",
      "uses": "Used in high-performance lighting, as an anesthetic in medical procedures, and in nuclear and aerospace applications.",
      "picture": "xenon.jpg"
    },
    {
      "name": "Radon",
      "symbol": "Rn",
      "atomic_number": 86,
      "atomic_mass": 222.0,
      "summary": "Radon is a radioactive noble gas. It is used in some medical treatments and as a tracer in scientific research.",
      "founded_by": "Friedrich Ernst Dorn",
      "state_of_matter": "Gas",
      "melting_point": 202.0,
      "group": 18,
      "period": 6,
      "density": 0.00973,
      "ionization_energy": 1037.0,
      "electron_configuration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6",
      "uses": "Used in some medical treatments and as a tracer in scientific research, but its radioactivity limits its applications.",
      "picture": "radon.jpg"
    }
  ],

    "lanthanides": [
    {
      "name": "Lanthanum",
      "symbol": "La",
      "atomic_number": 57,
      "atomic_mass": 138.91,
      "summary": "Lanthanum is a rare-earth metal. It is used in certain types of lighting and as a component in rechargeable batteries.",
      "founded_by": "Carl Gustaf Mosander",
      "state_of_matter": "Solid",
      "melting_point": 1193.15,
      "group": "N/A",
      "period": 6,
      "density": 6.15,
      "ionization_energy": 538.1,
      "electron_configuration": "[Xe] 5d1 6s2",
      "uses": "Used in some types of lighting, rechargeable batteries, and certain electronic devices.",
      "picture": "lanthanum.jpg"
    },
    {
      "name": "Cerium",
      "symbol": "Ce",
      "atomic_number": 58,
      "atomic_mass": 140.12,
      "summary": "Cerium is a rare-earth metal. It is used in catalysts, as a polishing agent, and in certain types of glass.",
      "founded_by": "Wilhelm Hisinger and Jöns Jacob Berzelius",
      "state_of_matter": "Solid",
      "melting_point": 1068.15,
      "group": "N/A",
      "period": 6,
      "density": 6.77,
      "ionization_energy": 534.4,
      "electron_configuration": "[Xe] 4f1 5d1 6s2",
      "uses": "Used in catalysts, as a polishing agent, and in the production of glass.",
      "picture": "cerium.jpg"
    },
    {
      "name": "Praseodymium",
      "symbol": "Pr",
      "atomic_number": 59,
      "atomic_mass": 140.91,
      "summary": "Praseodymium is a rare-earth metal. It is used in certain types of glass and as an alloying agent in some alloys.",
      "founded_by": "Carl Auer von Welsbach",
      "state_of_matter": "Solid",
      "melting_point": 1208.15,
      "group": "N/A",
      "period": 6,
      "density": 6.77,
      "ionization_energy": 527.0,
      "electron_configuration": "[Xe] 4f3 6s2",
      "uses": "Used in certain types of glass and as an alloying agent in some alloys.",
      "picture": "praseodymium.jpg"
    },
    {
      "name": "Neodymium",
      "symbol": "Nd",
      "atomic_number": 60,
      "atomic_mass": 144.24,
      "summary": "Neodymium is a rare-earth metal. It is used in high-strength magnets and in some types of glass.",
      "founded_by": "Carl Auer von Welsbach",
      "state_of_matter": "Solid",
      "melting_point": 1297.15,
      "group": "N/A",
      "period": 6,
      "density": 7.01,
      "ionization_energy": 533.1,
      "electron_configuration": "[Xe] 4f4 6s2",
      "uses": "Used in high-strength magnets, lasers, and certain types of glass.",
      "picture": "neodymium.jpg"
    },
    {
      "name": "Promethium",
      "symbol": "Pm",
      "atomic_number": 61,
      "atomic_mass": 145.0,
      "summary": "Promethium is a radioactive rare-earth element. It has limited practical uses due to its radioactivity.",
      "founded_by": "Isidor Isaac Rabi and Charles D. Coryell",
      "state_of_matter": "Solid",
      "melting_point": 1311.15,
      "group": "N/A",
      "period": 6,
      "density": 7.26,
      "ionization_energy": 540.0,
      "electron_configuration": "[Xe] 4f5 6s2",
      "uses": "Limited practical uses due to its radioactivity, primarily in nuclear batteries and scientific research.",
      "picture": "promethium.jpg"
    },
    {
      "name": "Samarium",
      "symbol": "Sm",
      "atomic_number": 62,
      "atomic_mass": 150.36,
      "summary": "Samarium is a rare-earth metal. It is used in magnets and as a neutron absorber in nuclear reactors.",
      "founded_by": "Lecoq de Boisbaudran",
      "state_of_matter": "Solid",
      "melting_point": 1345.15,
      "group": "N/A",
      "period": 6,
      "density": 7.52,
      "ionization_energy": 544.5,
      "electron_configuration": "[Xe] 4f6 6s2",
      "uses": "Used in permanent magnets, control rods in nuclear reactors, and certain ceramics.",
      "picture": "samarium.jpg"
    },
    {
      "name": "Europium",
      "symbol": "Eu",
      "atomic_number": 63,
      "atomic_mass": 152.0,
      "summary": "Europium is a rare-earth metal. It is used in phosphors for color displays and in some types of lighting.",
      "founded_by": "Eugène-Antole Demarçay",
      "state_of_matter": "Solid",
      "melting_point": 1095.15,
      "group": "N/A",
      "period": 6,
      "density": 5.24,
      "ionization_energy": 547.1,
      "electron_configuration": "[Xe] 4f7 6s2",
      "uses": "Used in color television phosphors, certain types of lighting, and some security features in banknotes.",
      "picture": "europium.jpg"
    },
    {
      "name": "Gadolinium",
      "symbol": "Gd",
      "atomic_number": 64,
      "atomic_mass": 157.25,
      "summary": "Gadolinium is a rare-earth metal. It is used in magnetic resonance imaging (MRI) contrast agents and some alloys.",
      "founded_by": "Jean Charles Galissard de Marignac",
      "state_of_matter": "Solid",
      "melting_point": 1585.15,
      "group": "N/A",
      "period": 6,
      "density": 7.90,
      "ionization_energy": 593.4,
      "electron_configuration": "[Xe] 4f7 5d1 6s2",
      "uses": "Used in MRI contrast agents, as a neutron absorber, and in certain alloys.",
      "picture": "gadolinium.jpg"
    },
    {
      "name": "Terbium",
      "symbol": "Tb",
      "atomic_number": 65,
      "atomic_mass": 158.93,
      "summary": "Terbium is a rare-earth metal. It is used in phosphors for color television tubes and certain electronic devices.",
      "founded_by": "Carl Gustaf Mosander",
      "state_of_matter": "Solid",
      "melting_point": 1629.15,
      "group": "N/A",
      "period": 6,
      "density": 8.23,
      "ionization_energy": 565.8,
      "electron_configuration": "[Xe] 4f9 6s2",
      "uses": "Used in color television phosphors, certain electronic devices, and as a stabilizer in fuel cells.",
      "picture": "terbium.jpg"
    },
    {
      "name": "Dysprosium",
      "symbol": "Dy",
      "atomic_number": 66,
      "atomic_mass": 162.50,
      "summary": "Dysprosium is a rare-earth metal. It is used in high-strength magnets and in some types of lighting.",
      "founded_by": "Lecoq de Boisbaudran",
      "state_of_matter": "Solid",
      "melting_point": 1680.15,
      "group": "N/A",
      "period": 6,
      "density": 8.55,
      "ionization_energy": 573.0,
      "electron_configuration": "[Xe] 4f10 6s2",
      "uses": "Used in high-strength magnets, in some types of lighting, and in nuclear reactor control rods.",
      "picture": "dysprosium.jpg"
    },
    {
      "name": "Holmium",
      "symbol": "Ho",
      "atomic_number": 67,
      "atomic_mass": 164.93,
      "summary": "Holmium is a rare-earth metal. It is used in some electronic devices and as a colorant in glass and ceramics.",
      "founded_by": "Per Teodor Cleve",
      "state_of_matter": "Solid",
      "melting_point": 1743.15,
      "group": "N/A",
      "period": 6,
      "density": 8.79,
      "ionization_energy": 581.0,
      "electron_configuration": "[Xe] 4f11 6s2",
      "uses": "Used in certain electronic devices, as a colorant in glass and ceramics, and in nuclear control rods.",
      "picture": "holmium.jpg"
    },
    {
      "name": "Erbium",
      "symbol": "Er",
      "atomic_number": 68,
      "atomic_mass": 167.26,
      "summary": "Erbium is a rare-earth metal. It is used in some types of lasers, as a colorant, and in nuclear control rods.",
      "founded_by": "Carl Gustaf Mosander",
      "state_of_matter": "Solid",
      "melting_point": 1802.15,
      "group": "N/A",
      "period": 6,
      "density": 9.07,
      "ionization_energy": 589.3,
      "electron_configuration": "[Xe] 4f12 6s2",
      "uses": "Used in fiber-optic amplifiers, as a colorant in glass, and in nuclear reactor control rods.",
      "picture": "erbium.jpg"
    },
    {
      "name": "Thulium",
      "symbol": "Tm",
      "atomic_number": 69,
      "atomic_mass": 168.93,
      "summary": "Thulium is a rare-earth metal. It is used in some medical devices and as a neutron source in portable X-ray devices.",
      "founded_by": "Per Teodor Cleve",
      "state_of_matter": "Solid",
      "melting_point": 1818.15,
      "group": "N/A",
      "period": 6,
      "density": 9.32,
      "ionization_energy": 596.7,
      "electron_configuration": "[Xe] 4f13 6s2",
      "uses": "Used in some medical devices, as a neutron source, and in portable X-ray devices.",
      "picture": "thulium.jpg"
    },
    {
      "name": "Ytterbium",
      "symbol": "Yb",
      "atomic_number": 70,
      "atomic_mass": 173.05,
      "summary": "Ytterbium is a rare-earth metal. It is used in some types of lasers and as a gamma-ray source in portable X-ray devices.",
      "founded_by": "Jean Charles Galissard de Marignac",
      "state_of_matter": "Solid",
      "melting_point": 1097.15,
      "group": "N/A",
      "period": 6,
      "density": 6.90,
      "ionization_energy": 603.4,
      "electron_configuration": "[Xe] 4f14 6s2",
      "uses": "Used in certain types of lasers, as a gamma-ray source, and in portable X-ray devices.",
      "picture": "ytterbium.jpg"
    },
    {
      "name": "Lutetium",
      "symbol": "Lu",
      "atomic_number": 71,
      "atomic_mass": 175.94,
      "summary": "Lutetium is a rare-earth metal. It is used in certain types of radiation therapy and as a catalyst in some chemical reactions.",
      "founded_by": "Carl Auer von Welsbach",
      "state_of_matter": "Solid",
      "melting_point": 1923.15,
      "group": "N/A",
      "period": 6,
      "density": 9.84,
      "ionization_energy": 523.5,
      "electron_configuration": "[Xe] 4f14 5d1 6s2",
      "uses": "Used in radiation therapy for cancer treatment and as a catalyst in some chemical reactions.",
      "picture": "lutetium.jpg"
    }
  ],

    "actinides": [
    {
      "name": "Actinium",
      "symbol": "Ac",
      "atomic_number": 89,
      "atomic_mass": 227.0,
      "summary": "Actinium is a radioactive element. It has limited practical uses due to its scarcity and radioactivity.",
      "founded_by": "Friedrich Oskar Giesel",
      "state_of_matter": "Solid",
      "melting_point": 1323.15,
      "group": "N/A",
      "period": 7,
      "density": 10.07,
      "ionization_energy": 499.0,
      "electron_configuration": "[Rn] 6d1 7s2",
      "uses": "Limited practical uses due to its scarcity and radioactivity, primarily in scientific research.",
      "picture": "actinium.jpg"
    },
    {
      "name": "Thorium",
      "symbol": "Th",
      "atomic_number": 90,
      "atomic_mass": 232.04,
      "summary": "Thorium is a radioactive element. It has been used in nuclear reactors and as a catalyst in some chemical reactions.",
      "founded_by": "Jöns Jacob Berzelius",
      "state_of_matter": "Solid",
      "melting_point": 2023.15,
      "group": "N/A",
      "period": 7,
      "density": 11.72,
      "ionization_energy": 587.0,
      "electron_configuration": "[Rn] 6d2 7s2",
      "uses": "Used in nuclear reactors, as a catalyst in some chemical reactions, and in certain high-strength materials.",
      "picture": "thorium.jpg"
    },
    {
      "name": "Protactinium",
      "symbol": "Pa",
      "atomic_number": 91,
      "atomic_mass": 231.04,
      "summary": "Protactinium is a radioactive element. It has limited practical uses due to its scarcity and radioactivity.",
      "founded_by": "Otto Hahn and Lise Meitner",
      "state_of_matter": "Solid",
      "melting_point": 1841.15,
      "group": "N/A",
      "period": 7,
      "density": 15.37,
      "ionization_energy": 568.3,
      "electron_configuration": "[Rn] 5f2 6d1 7s2",
      "uses": "Limited practical uses due to its scarcity and radioactivity, primarily in scientific research.",
      "picture": "protactinium.jpg"
    },
    {
      "name": "Uranium",
      "symbol": "U",
      "atomic_number": 92,
      "atomic_mass": 238.03,
      "summary": "Uranium is a radioactive element. It is used as fuel in nuclear reactors and in the production of nuclear weapons.",
      "founded_by": "Martin Heinrich Klaproth",
      "state_of_matter": "Solid",
      "melting_point": 1405.15,
      "group": "N/A",
      "period": 7,
      "density": 19.05,
      "ionization_energy": 597.6,
      "electron_configuration": "[Rn] 5f3 6d1 7s2",
      "uses": "Used as fuel in nuclear reactors, in nuclear weapons production, and in some scientific research.",
      "picture": "uranium.jpg"
    },
    {
      "name": "Neptunium",
      "symbol": "Np",
      "atomic_number": 93,
      "atomic_mass": 237.0,
      "summary": "Neptunium is a radioactive element. It has limited practical uses due to its scarcity and radioactivity.",
      "founded_by": "Edwin McMillan and Philip H. Abelson",
      "state_of_matter": "Solid",
      "melting_point": 917.15,
      "group": "N/A",
      "period": 7,
      "density": 20.25,
      "ionization_energy": 604.5,
      "electron_configuration": "[Rn] 5f4 6d1 7s2",
      "uses": "Limited practical uses due to its scarcity and radioactivity, primarily in scientific research.",
      "picture": "neptunium.jpg"
    },
    {
      "name": "Plutonium",
      "symbol": "Pu",
      "atomic_number": 94,
      "atomic_mass": 244.0,
      "summary": "Plutonium is a radioactive element. It is used in nuclear reactors and in the production of nuclear weapons.",
      "founded_by": "Glenn T. Seaborg, Ralph A. James, and Albert Ghiorso",
      "state_of_matter": "Solid",
      "melting_point": 913.15,
      "group": "N/A",
      "period": 7,
      "density": 19.86,
      "ionization_energy": 584.7,
      "electron_configuration": "[Rn] 5f6 7s2",
      "uses": "Used in nuclear reactors, in nuclear weapons production, and in some scientific research.",
      "picture": "plutonium.jpg"
    },
    {
      "name": "Americium",
      "symbol": "Am",
      "atomic_number": 95,
      "atomic_mass": 243.0,
      "summary": "Americium is a radioactive element. It is used in smoke detectors and in certain types of industrial devices.",
      "founded_by": "Glenn T. Seaborg, Ralph A. James, and Albert Ghiorso",
      "state_of_matter": "Solid",
      "melting_point": 1449.15,
      "group": "N/A",
      "period": 7,
      "density": 13.67,
      "ionization_energy": 578.5,
      "electron_configuration": "[Rn] 5f7 7s2",
      "uses": "Used in smoke detectors, as a neutron source, and in some industrial devices.",
      "picture": "americium.jpg"
    },
    {
      "name": "Curium",
      "symbol": "Cm",
      "atomic_number": 96,
      "atomic_mass": 247.0,
      "summary": "Curium is a radioactive element. It is primarily used in scientific research due to its radioactivity.",
      "founded_by": "Glenn T. Seaborg, Ralph A. James, and Albert Ghiorso",
      "state_of_matter": "Solid",
      "melting_point": 1613.15,
      "group": "N/A",
      "period": 7,
      "density": 13.51,
      "ionization_energy": 581.9,
      "electron_configuration": "[Rn] 5f7 6d1 7s2",
      "uses": "Primarily used in scientific research due to its radioactivity.",
      "picture": "curium.jpg"
    },
    {
      "name": "Berkelium",
      "symbol": "Bk",
      "atomic_number": 97,
      "atomic_mass": 247.0,
      "summary": "Berkelium is a radioactive element. It is primarily used in scientific research due to its radioactivity.",
      "founded_by": "Glenn T. Seaborg, Ralph A. James, and Albert Ghiorso",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "N/A",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f9 7s2",
      "uses": "Primarily used in scientific research due to its radioactivity.",
      "picture": "berkelium.jpg"
    },
    {
      "name": "Californium",
      "symbol": "Cf",
      "atomic_number": 98,
      "atomic_mass": 251.0,
      "summary": "Californium is a radioactive element. It is used in some types of neutron sources for scientific research.",
      "founded_by": "Albert Ghiorso, Ralph A. James, and Glenn T. Seaborg",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "N/A",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f10 7s2",
      "uses": "Used in some types of neutron sources for scientific research.",
      "picture": "californium.jpg"
    },
    {
      "name": "Einsteinium",
      "symbol": "Es",
      "atomic_number": 99,
      "atomic_mass": 252.0,
      "summary": "Einsteinium is a radioactive element. It is primarily used in scientific research due to its radioactivity.",
      "founded_by": "Albert Ghiorso, Ralph A. James, and Glenn T. Seaborg",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "N/A",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f11 7s2",
      "uses": "Primarily used in scientific research due to its radioactivity.",
      "picture": "einsteinium.jpg"
    },
    {
      "name": "Fermium",
      "symbol": "Fm",
      "atomic_number": 100,
      "atomic_mass": 257.0,
      "summary": "Fermium is a radioactive element. It is primarily used in scientific research due to its radioactivity.",
      "founded_by": "Albert Ghiorso, Ralph A. James, and Glenn T. Seaborg",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "N/A",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f12 7s2",
      "uses": "Primarily used in scientific research due to its radioactivity.",
      "picture": "fermium.jpg"
    },
    {
      "name": "Mendelevium",
      "symbol": "Md",
      "atomic_number": 101,
      "atomic_mass": 258.0,
      "summary": "Mendelevium is a radioactive element. It is primarily used in scientific research due to its radioactivity.",
      "founded_by": "Albert Ghiorso, Ralph A. James, and Glenn T. Seaborg",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "N/A",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f13 7s2",
      "uses": "Primarily used in scientific research due to its radioactivity.",
      "picture": "mendelevium.jpg"
    },
    {
      "name": "Nobelium",
      "symbol": "No",
      "atomic_number": 102,
      "atomic_mass": 259.0,
      "summary": "Nobelium is a radioactive element. It is primarily used in scientific research due to its radioactivity.",
      "founded_by": "Albert Ghiorso, Ralph A. James, and Glenn T. Seaborg",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "N/A",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 7s2",
      "uses": "Primarily used in scientific research due to its radioactivity.",
      "picture": "nobelium.jpg"
    },
    {
      "name": "Lawrencium",
      "symbol": "Lr",
      "atomic_number": 103,
      "atomic_mass": 262.0,
      "summary": "Lawrencium is a radioactive element. It is primarily used in scientific research due to its radioactivity.",
      "founded_by": "Albert Ghiorso, Ralph A. James, and Glenn T. Seaborg",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "N/A",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d1 7s2",
      "uses": "Primarily used in scientific research due to its radioactivity.",
      "picture": "lawrencium.jpg"
    }
  ],

    "other_elements": [
    {
      "name": "Meitnerium",
      "symbol": "Mt",
      "atomic_number": 109,
      "atomic_mass": 278.0,
      "summary": "Meitnerium is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Peter Armbruster and Gottfried Münzenberg",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "9",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d7 7s2",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "meitnerium.jpg"
    },
    {
      "name": "Darmstadtium",
      "symbol": "Ds",
      "atomic_number": 110,
      "atomic_mass": 281.0,
      "summary": "Darmstadtium is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Peter Armbruster and Gottfried Münzenberg",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "10",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d9 7s1",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "darmstadtium.jpg"
    },
    {
      "name": "Roentgenium",
      "symbol": "Rg",
      "atomic_number": 111,
      "atomic_mass": 282.0,
      "summary": "Roentgenium is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Peter Armbruster and Gottfried Münzenberg",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "11",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d10 7s1",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "roentgenium.jpg"
    },
    {
      "name": "Copernicium",
      "symbol": "Cn",
      "atomic_number": 112,
      "atomic_mass": 285.0,
      "summary": "Copernicium is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Sigurd Hofmann and colleagues",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "12",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d10 7s2",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "copernicium.jpg"
    },
    {
      "name": "Nihonium",
      "symbol": "Nh",
      "atomic_number": 113,
      "atomic_mass": 284.0,
      "summary": "Nihonium is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Riken Institute and collaborators",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "13",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d10 7s2 7p1",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "nihonium.jpg"
    },
    {
      "name": "Flerovium",
      "symbol": "Fl",
      "atomic_number": 114,
      "atomic_mass": 289.0,
      "summary": "Flerovium is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Joint Institute for Nuclear Research and collaborators",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "14",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d10 7s2 7p2",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "flerovium.jpg"
    },
    {
      "name": "Moscovium",
      "symbol": "Mc",
      "atomic_number": 115,
      "atomic_mass": 290.0,
      "summary": "Moscovium is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Joint Institute for Nuclear Research and collaborators",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "15",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d10 7s2 7p3",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "moscovium.jpg"
    },
    {
      "name": "Livermorium",
      "symbol": "Lv",
      "atomic_number": 116,
      "atomic_mass": 293.0,
      "summary": "Livermorium is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Joint Institute for Nuclear Research and collaborators",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "16",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d10 7s2 7p4",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "Livermorium.jpg"
    },
    {
      "name": "Tennessine",
      "symbol": "Ts",
      "atomic_number": 117,
      "atomic_mass": 294.0,
      "summary": "Tennessine is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Oak Ridge National Laboratory and collaborators",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "17",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d10 7s2 7p5",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "tennessine.jpg"
    },
    {
      "name": "Oganesson",
      "symbol": "Og",
      "atomic_number": 118,
      "atomic_mass": 294.0,
      "summary": "Oganesson is a synthetic element. It has limited practical uses and is primarily used in scientific research.",
      "founded_by": "Joint Institute for Nuclear Research and collaborators",
      "state_of_matter": "Solid",
      "melting_point": "Unknown",
      "group": "18",
      "period": 7,
      "density": "Unknown",
      "ionization_energy": "Unknown",
      "electron_configuration": "[Rn] 5f14 6d10 7s2 7p6",
      "uses": "Limited practical uses, primarily in scientific research.",
      "picture": "oganesson.jpg"
    }
  ]

  }
}
